name: Pixeebot Fix
description: Upload SonarCloud file and trigger analysis

inputs:
  tool:
    description: >
      The supported code quality tool that produced the results being shared
      with Pixee. Allowed values: 'sonar', 'codeql', 'semgrep'
    required: true
  file:
    description: Path to the tool's results file to share with Pixee.
    required: false
  sonar-token:
    description: Token for authenticating requests to SonarCloud.
    required: false
  sonar-component-key:
    description: Key identifying the SonarCloud component to be analyzed.
    required: false
  sonar-api-url:
    description: Base URL of the SonarCloud API.
    default: https://sonarcloud.io/api

runs:
  using: "composite"
  steps:
    - name: Upload file to pixee
      uses: pixee/pixee-actions/upload-file@main
      with:
        file: ${{ inputs.file }}
        tool: ${{ inputs.tool }}
        sonar-token: ${{ inputs.sonar-token }}
        sonar-component-key: ${{ inputs.sonar-component-key }}
        sonar-api-url: ${{ inputs.sonar-api-url }}
    - name: Call trigger
      uses: pixee/pixee-actions/trigger@main
