name: Share Tool Results With Pixee
description:
  Sends results from a code quality tool to Pixee so that Pixee may
  automatically fix issues found.

inputs:
  tool:
    description: >
      The supported code quality tool that produced the results being shared
      with Pixee. Allowed values: 'sonar', 'codeql', 'semgrep'
    required: true
  file:
    description: Path to the tool's results file to share with Pixee.
    required: false
  sonar-token:
    description: Token for authenticating requests to SonarCloud.
    required: false
  sonar-component-key:
    description: Key identifying the SonarCloud component to be analyzed.
    required: false
  sonar-api-url:
    description: Base URL of the SonarCloud API.
    default: https://sonarcloud.io/api

runs:
  using: "node20"
  main: dist/index.js
