name: Pixeebot Find and Fix PR
description: Trigger Pixee analysis
author: Pixee
inputs:
  url:
    description: Endpoint URL where the analysis will be triggered.
    required: false
outputs:
  status:
    description: Status
runs:
  using: node20
  main: ../dist/trigger/index.js
