name: Analysis input

on:
  pull_request:
    types: [ opened ]

permissions:
  contents: read
  id-token: write

env:
  # Replace <sonar-organization> with the organization retrieved from sonarcloud
  SONAR_ORGANIZATION: <sonar-organization>
  # Replace <sonar-project-key> with the project key retrieved from sonarcloud
  SONAR_PROJECT_KEY: <sonar-project-key>

jobs:
  analysis-input:
    name: Upload SonarCloud file and trigger analysis
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep:1.51.0
    timeout-minutes: 6

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Semgrep cli
        run: semgrep --config auto . --sarif -o semgrep.sarif
      - name: Semgrep upload file
        uses: JesusCotlamee/pixee-actions/upload-file@main
        with:
          FILE: 'semgrep.sarif'
          # Replace with the specific property that identifies the tool related to the uploaded file. Allowed values: 'sonar', 'codeql', 'semgrep'
          TOOL: 'semgrep'
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@49e6cd3b187936a73b8280d59ffd9da69df63ec9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Replace <sonar-token> with the token retrieved from SonarCloud. Strongly recommend against hard coding the token directly into the workflow file. Instead, use GitHub Secrets to securely store and access sensitive information.
          SONAR_TOKEN: <sonar-token>
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
      - name: SonarCloud download
        shell: bash
        run: |
          URL="https://sonarcloud.io/api/issues/search?componentKeys=${{ env.SONAR_PROJECT_KEY }}&pullRequest=${{ github.event.number }}"
          curl -v "$URL" -o sonar_issues.json
      - name: Upload file and trigger analysis
        # Replace <latest-commit> with the latest stable commit available in pixee-actions
        uses: JesusCotlamee/pixee-actions/analysis-input@<latest-commit>
        with:
          FILE: sonar_issues.json
          # Replace with the specific property that identifies the tool related to the uploaded file. Allowed values: 'sonar', 'codeql', 'semgrep'
          TOOL: 'sonar'
