name: Pixeebot Fix

on:
  check_run:
    types: [ completed ]

permissions:
  id-token: write

env:
  # Replace <sonar-project-key> with the project key retrieved from sonarcloud
  SONAR_PROJECT_KEY: <sonar-project-key>

jobs:
  pixeebot-fix:
    name: Pixeebot Fix
    if: ${{ !startsWith(github.actor, 'pixee') && github.event.check_run.name == 'SonarCloud Code Analysis' }}
    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
      - name: Upload file and trigger analysis
        uses: pixee/pixee-actions/analysis-input@main
        with:
          # Replace with the specific property that identifies the tool related to the uploaded file. Allowed values: 'sonar', 'codeql', 'semgrep'
          tool: 'sonar'
