name: Fix DefectDojo Findings with Pixeebot
on:
  check_run:
    types: [completed]

permissions:
  id-token: write

jobs:
  share:
    name: Upload DefectDojo Findings to Pixeebot
    runs-on: ubuntu-latest
    # TODO check condition event
    # if: ${{ github.event.check_run.name == 'SonarCloud Code Analysis' }}
    steps:
      # TODO update commit hash to version
      - uses: pixee/upload-tool-results-action@71a73d2fb01d4e78e8180abce80fc24cefc24ccb
        with:
          tool: defectdojo
          defectdojo-token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo-api-url: https://pixee-test.cloud.defectdojo.com/api
          # defectdojo-product-name: pygoat_demo
