name: Fix DefectDojo Findings with Pixeebot
on:
  pull_request:
    branches:
      - master

permissions:
  id-token: write

jobs:
  share:
    name: Upload DefectDojo Findings to Pixeebot
    runs-on: ubuntu-latest
    steps:
      # TODO update commit hash to version
      - uses: pixee/upload-tool-results-action@dca12668dd9cb999cd4a441e81ed67cb8d5d8b2d
        with:
          tool: defectdojo
          defectdojo-token: ${{ secrets.DEFECTDOJO_TOKEN }}
          defectdojo-api-url: https://pixee-test.cloud.defectdojo.com
          defectdojo-product-name: pygoat_demo
