name: Upload file

on:
  pull_request:
    types: [ opened ]

permissions:
  id-token: write

jobs:
  upload-file:
    runs-on: ubuntu-latest
    name: Upload file
    timeout-minutes: 2

    steps:
      - name: Checkout repository
        # Replace <latest-commit> with the latest stable commit available in actions-checkout (https://github.com/actions/checkout)
        uses: actions/checkout@<latest-commit>
      - name: Upload file
        # Replace <latest-commit> with the latest stable commit available in pixee-actions (https://github.com/pixee/pixee-actions)
        uses: pixee/pixee-actions/upload-file@<latest-commit>
        with:
          # Replace <file> with the file to be uploaded.
          file: <file>
          # Replace <tool> with the specific property that identifies the tool related to the uploaded file. Allowed values: 'sonar', 'codeql', 'semgrep'
          tool: <tool>
