name: Share Static Analysis with Pixeebot

on:
  pull_request:
    types: [ opened ]

permissions:
  id-token: write

jobs:
  share-analysis-with-pixeebot:
    runs-on: ubuntu-latest
    name: Share Static Analysis with Pixeebot
    timeout-minutes: 2

    steps:
      - name: Upload file
        uses: pixee/pixee-actions/upload-file@main
        with:
          # Replace <tool> with the specific property that identifies the tool related to the uploaded file. Allowed values: 'sonar', 'codeql', 'semgrep'
          tool: <tool>
          sonar-token: ${{ secrets.SONAR_TOKEN }}
