name: Upload file
description: Upload file to Pixee
author: Pixee
inputs:
  file:
    description: File to be uploaded.
    required: true
  tool:
    description: >
      Specific property that identifies the tool related to the uploaded file.
      Allowed values: 'sonar', 'codeql', 'semgrep'
    required: true
  url:
    description: Endpoint URL where the file will be uploaded.
    required: false
outputs:
  status:
    description: Status
runs:
  using: node20
  main: ../dist/upload-file/index.js
